language: node_js
node_js:
    - "6.4.0"
    - "11.0.0"
before_install: 
    - npm install mocha -g
    - npm install chai -g
    - npm install coveralls -g
    - npm install istanbul -g
    - npm install nyc -g
script: npm test